# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['cutter.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('config/config.json', 'config'),
        ('assets', 'assets'),
    ],
    hiddenimports=[
        "openpyxl",
        "openpyxl.cell._writer",
        "openpyxl.reader.excel",
        "openpyxl.writer.excel",
        "reportlab",
        "reportlab.lib",
        "reportlab.platypus",
        "folium",
        "folium.plugins",
        "PyQt6",
        "PyQt6.QtCore",
        "PyQt6.QtGui",
        "PyQt6.QtWidgets",
        "PyQt6.QtNetwork",
        "PyQt6.QtPrintSupport",
        "PyQt6.QtOpenGL",
        "PyQt6.QtOpenGLWidgets",
        "PyQt6.QtPositioning",
        "PyQt6.QtWebChannel",
        "PyQt6.QtWebEngineCore",
        "PyQt6.QtWebEngineWidgets",
        "PyQt6.QtWebEngineQuick",
        "scapy",
        "scapy.all",
        "python_dotenv",
        "requests",
        "requests.api",
        "requests.models",
        "requests.sessions",
        "requests.adapters",
        "requests.auth",
        "requests.cookies",
        "requests.exceptions",
        "requests_file",
        "urllib3",
        "urllib3.util",
        "urllib3.util.retry",
        "certifi",
        "charset_normalizer",
        "idna",
        "branca",
        "jinja2",
        "markupsafe",
        "xyzservices",
        "numpy",
        "openpyxl.chart",
        "openpyxl.drawing",
        "openpyxl.worksheet",
        "reportlab.pdfgen",
        "reportlab.platypus",
        "reportlab.graphics",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "PyQt5", "PySide6",
        "torch", "torchvision", "torchaudio",
        "scipy", "pandas",
        "matplotlib", "IPython", "jupyter",
        "notebook", "qtconsole",
        "tkinter", "_tkinter",
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='cutter',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='cutter',
)
