import html
import logging
from typing import Dict

from src.export.base import Exporter
from src.models.session import SessionReport

logger = logging.getLogger(__name__)


class HtmlExporter(Exporter):
    def export(self, report: SessionReport, peers: Dict[str, Dict], path: str) -> bool:
        try:
            rows = ""
            for ip, data in peers.items():
                intel = data.get("intel")
                stats = data.get("stats", {})
                ip_type = data.get("type", "UNKNOWN")
                color = "#0f0" if ip_type == "P2P_PEER" else "#fa0"
                ver = "v6" if (intel and intel.is_ipv6) else "v4"
                rows += f"""<tr>
                    <td>{html.escape(ip)} ({html.escape(ver)})</td>
                    <td style="color:{html.escape(color)};font-weight:bold">{html.escape(ip_type)}</td>
                    <td>{html.escape(intel.isp if intel else 'Unknown')}</td>
                    <td>{html.escape(intel.city if intel else 'Unknown')}</td>
                    <td>{html.escape(intel.country if intel else 'Unknown')}</td>
                    <td>{stats.get('packets', 0)}</td>
                    <td>{stats.get('bytes', 0):,}</td>
                </tr>"""
            html_content = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>VoIP Report</title>
<style>
body {{ font-family: 'Consolas', monospace; background: #000; color: #0f0; padding: 20px; }}
h1 {{ color: #0ff; border-bottom: 2px solid #0f0; }}
table {{ border-collapse: collapse; width: 100%; margin-top: 20px; }}
th, td {{ border: 1px solid #0f0; padding: 8px; text-align: left; }}
th {{ background: #001a00; }}
.summary {{ background: #001a1a; padding: 15px; border: 1px solid #0ff; }}
</style></head><body>
<h1>VoIP Analysis Report</h1>
<div class="summary">
<p><b>Timestamp:</b> {html.escape(report.timestamp)}</p>
<p><b>Duration:</b> {report.duration_seconds:.1f}s</p>
<p><b>Total Packets:</b> {report.total_packets}</p>
<p><b>P2P Peers:</b> {report.p2p_count}</p>
<p><b>Relay Servers:</b> {report.relay_count}</p>
<p><b>Countries:</b> {html.escape(', '.join(report.countries) or 'N/A')}</p>
</div>
<table><tr><th>IP</th><th>Type</th><th>ISP</th><th>City</th><th>Country</th><th>Packets</th><th>Bytes</th></tr>
{rows}</table>
<p style="margin-top:20px;color:#888">Generated by VoIP Analyzer v3.1.0</p>
</body></html>"""
            with open(path, "w", encoding="utf-8") as f:
                f.write(html_content)
            logger.info("HTML exported: %s", path)
            return True
        except OSError as e:
            logger.error("HTML export failed: %s", e)
            return False
