"""Markdown report exporter (no external dependencies)."""

import logging

from src.export.base import Exporter
from src.models.session import SessionReport

logger = logging.getLogger(__name__)


class MarkdownExporter(Exporter):
    def export(self, report: SessionReport, peers: dict[str, dict], path: str) -> bool:
        try:
            lines = [
                "# VoIP Analysis Report",
                "",
                f"- **Timestamp:** {report.timestamp}",
                f"- **Duration:** {report.duration_seconds:.1f}s",
                f"- **Total Packets:** {report.total_packets}",
                f"- **Total Bytes:** {report.total_bytes}",
                f"- **P2P Peers:** {report.p2p_count}",
                f"- **Relay Servers:** {report.relay_count}",
                f"- **Countries:** {', '.join(report.countries) or 'N/A'}",
                "",
                "## Peers",
                "",
                "| IP | Type | ISP | City | Country | ASN | Packets | Bytes | Confidence |",
                "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
            ]
            for ip, data in peers.items():
                intel = data.get("intel")
                stats = data.get("stats", {})
                conf = f"{intel.confidence:.2f}" if intel else "0.00"
                lines.append(
                    f"| {ip} | {data.get('type', 'UNKNOWN')} | "
                    f"{intel.isp if intel else 'Unknown'} | "
                    f"{intel.city if intel else 'Unknown'} | "
                    f"{intel.country if intel else 'Unknown'} | "
                    f"{intel.asn if intel else 'N/A'} | "
                    f"{stats.get('packets', 0)} | {stats.get('bytes', 0)} | "
                    f"{conf} |"
                )
            lines.append("")
            lines.append("_Generated by VoIP Analyzer v3.2.0_")
            with open(path, "w", encoding="utf-8") as f:
                f.write("\n".join(lines))
            logger.info("Markdown exported: %s", path)
            return True
        except OSError as exc:
            logger.error("Markdown export failed: %s", exc)
            return False
